"use client";

import { FormEvent, useEffect, useState } from "react";

type Tab = "today" | "study" | "money" | "sport" | "review";
type Subject = "数学一" | "英语一" | "政治" | "自动控制原理";
type Task = { id:number; subject:Subject; text:string; date:string; done:boolean };
type Study = { id:number; subject:Subject; minutes:number; date:string; note:string };
type Expense = { id:number; amount:number; category:string; note:string; date:string };
type Workout = { id:number; type:string; minutes:number; distance:number; date:string; note:string };
type Modal = {type:"task";record?:Task}|{type:"study";record?:Study}|{type:"expense";record?:Expense}|{type:"workout";record?:Workout}|null;

const SUBJECTS:{name:Subject;color:string;short:string}[]=[
  {name:"数学一",color:"#e79a5c",short:"数"},{name:"英语一",color:"#7fa8a1",short:"英"},
  {name:"政治",color:"#bc8b97",short:"政"},{name:"自动控制原理",color:"#9995c9",short:"控"},
];
const THEMES=[{id:"lilac",name:"淡紫"},{id:"mint",name:"薄荷"},{id:"peach",name:"蜜桃"},{id:"blue",name:"雾蓝"},{id:"night",name:"夜色"}] as const;
type Theme=typeof THEMES[number]["id"];
const dayKey=(d=new Date())=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
const previousDay=()=>{const d=new Date();d.setDate(d.getDate()-1);return dayKey(d)};
const mins=(n:number)=>n>=60?`${Math.floor(n/60)}h${n%60?` ${n%60}m`:""}`:`${n}m`;
const dateText=(v:string)=>new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric",weekday:"short"}).format(new Date(`${v}T12:00:00`));
function read<T>(key:string,fallback:()=>T){try{const v=localStorage.getItem(key);return v?JSON.parse(v) as T:fallback()}catch{return fallback()}}
function useSaved<T>(key:string,fallback:()=>T){const [value,setValue]=useState<T>(()=>typeof window==="undefined"?fallback():read(key,fallback));useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}},[key,value]);return [value,setValue] as const}
function taskMigration():Task[]{try{const raw=localStorage.getItem("kaoyan.tasks.v4")||localStorage.getItem("night-tasks-v3")||localStorage.getItem("night-tasks-v2")||"[]";return (JSON.parse(raw) as Partial<Task>[]).map((t,i)=>({id:t.id||Date.now()+i,subject:(t.subject as Subject)||"数学一",text:t.text||"未命名任务",done:Boolean(t.done),date:typeof t.date==="string"?t.date:previousDay()}))}catch{return []}}

export default function Home(){
  const [ready,setReady]=useState(false);
  useEffect(()=>setReady(true),[]);
  const [tab,setTab]=useState<Tab>("today");
  const [theme,setTheme]=useSaved<Theme>("kaoyan.theme.v1",()=>"lilac");
  const [themeOpen,setThemeOpen]=useState(false);
  const [tasks,setTasks]=useSaved<Task[]>("kaoyan.tasks.v4",taskMigration);
  const [studies,setStudies]=useSaved<Study[]>("kaoyan.studies.v2",()=>read("night-study-sessions",()=>[]).map((x:Study&{seconds?:number})=>({...x,minutes:x.minutes||Math.max(1,Math.round((x.seconds||0)/60))})));
  const [expenses,setExpenses]=useSaved<Expense[]>("kaoyan.expenses.v2",()=>read("night-expenses",()=>[]));
  const [workouts,setWorkouts]=useSaved<Workout[]>("kaoyan.workouts.v2",()=>read("night-workouts",()=>[]).map((x:Workout&{duration?:number})=>({...x,minutes:x.minutes||x.duration||0})));
  const [target,setTarget]=useSaved<string>("kaoyan.target.v2",()=>read("night-target",()=>"2026-12-20"));
  const [activeDate,setActiveDate]=useState(dayKey());
  const [focus,setFocus]=useState<Subject>("数学一");
  type TimerState={running:boolean;started:number|null;elapsed:number;unit?:"seconds"};
  const [timer,setTimer]=useSaved<TimerState>("kaoyan.timer.v2",()=>({running:false,started:null,elapsed:0,unit:"seconds"}));
  const [modal,setModal]=useState<Modal>(null);
  const [now,setNow]=useState(Date.now());
  const [reviewMonth,setReviewMonth]=useState(dayKey().slice(0,7));
  useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id)},[]);
  useEffect(()=>{document.documentElement.style.setProperty("--hour-tone",new Date(now).getHours()<12?"#7fa8a1":new Date(now).getHours()<18?"#9b91c9":"#c88782")},[now]);
  useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);
  const today=dayKey(), yesterday=previousDay();
  const todayTasks=tasks.filter(x=>x.date===today), selectedTasks=tasks.filter(x=>x.date===activeDate);
  const selectedStudies=studies.filter(x=>x.date===activeDate), selectedExpenses=expenses.filter(x=>x.date===activeDate), selectedWorkouts=workouts.filter(x=>x.date===activeDate);
  const todayMinutes=studies.filter(x=>x.date===today).reduce((s,x)=>s+x.minutes,0), todaySpend=expenses.filter(x=>x.date===today).reduce((s,x)=>s+x.amount,0), todayMovement=workouts.filter(x=>x.date===today).reduce((s,x)=>s+x.minutes,0);
  const taskProgress=todayTasks.length?Math.round(todayTasks.filter(x=>x.done).length/todayTasks.length*100):0;
  const days=Math.max(0,Math.ceil((new Date(`${target}T00:00:00`).getTime()-now)/86400000));
  const savedSeconds=timer.unit==="seconds"?timer.elapsed:timer.elapsed*60;
  const timerSeconds=timer.running&&timer.started?Math.max(savedSeconds,Math.floor((now-timer.started)/1000)):savedSeconds;
  const timerMinutes=Math.max(1,Math.round(timerSeconds/60));
  const monthStudies=studies.filter(x=>x.date.startsWith(reviewMonth)), monthExpenses=expenses.filter(x=>x.date.startsWith(reviewMonth)), monthWorkouts=workouts.filter(x=>x.date.startsWith(reviewMonth));
  const monthDays=new Set([...monthStudies,...monthExpenses,...monthWorkouts,...tasks.filter(x=>x.date.startsWith(reviewMonth))].map(x=>x.date));
  const daysInMonth=new Date(Number(reviewMonth.slice(0,4)),Number(reviewMonth.slice(5)),0).getDate();
  const dailyDetails=Array.from({length:daysInMonth},(_,i)=>{const date=`${reviewMonth}-${String(i+1).padStart(2,"0")}`;return {date,tasks:tasks.filter(x=>x.date===date),studies:studies.filter(x=>x.date===date),expenses:expenses.filter(x=>x.date===date),workouts:workouts.filter(x=>x.date===date)}}).filter(x=>x.tasks.length||x.studies.length||x.expenses.length||x.workouts.length).reverse();
  const greeting=new Date(now).getHours()<11?"早上好":new Date(now).getHours()<18?"下午好":"晚上好";
  const editTask=modal?.type==="task"?modal.record:undefined, editStudy=modal?.type==="study"?modal.record:undefined, editExpense=modal?.type==="expense"?modal.record:undefined, editWorkout=modal?.type==="workout"?modal.record:undefined;
  const remove=(label:string,run:()=>void)=>{if(window.confirm(`确定删除这条${label}吗？`))run()};
  const saveTask=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const x:Task={id:editTask?.id||Date.now(),subject:f.get("subject") as Subject,text:String(f.get("text")).trim(),date:String(f.get("date")),done:editTask?.done||false};setTasks(v=>editTask?v.map(y=>y.id===x.id?x:y):[x,...v]);setActiveDate(x.date);setModal(null)};
  const saveStudy=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const x:Study={id:editStudy?.id||Date.now(),subject:f.get("subject") as Subject,minutes:Number(f.get("minutes")),date:String(f.get("date")),note:String(f.get("note"))};setStudies(v=>editStudy?v.map(y=>y.id===x.id?x:y):[x,...v]);setActiveDate(x.date);setModal(null)};
  const saveExpense=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const x:Expense={id:editExpense?.id||Date.now(),amount:Number(f.get("amount")),category:String(f.get("category")),date:String(f.get("date")),note:String(f.get("note"))};setExpenses(v=>editExpense?v.map(y=>y.id===x.id?x:y):[x,...v]);setActiveDate(x.date);setModal(null)};
  const saveWorkout=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const x:Workout={id:editWorkout?.id||Date.now(),type:String(f.get("type")),minutes:Number(f.get("minutes")),distance:Number(f.get("distance"))||0,date:String(f.get("date")),note:String(f.get("note"))};setWorkouts(v=>editWorkout?v.map(y=>y.id===x.id?x:y):[x,...v]);setActiveDate(x.date);setModal(null)};
  const toggleTimer=()=>setTimer(t=>{const seconds=t.unit==="seconds"?t.elapsed:t.elapsed*60;return t.running?{running:false,started:null,elapsed:t.started?Math.floor((Date.now()-t.started)/1000):seconds,unit:"seconds"}:{running:true,started:Date.now()-seconds*1000,elapsed:seconds,unit:"seconds"}});
  const finishTimer=()=>{if(!timerSeconds)return;setStudies(v=>[{id:Date.now(),subject:focus,minutes:timerMinutes,date:today,note:`专注计时 ${String(Math.floor(timerSeconds/60)).padStart(2,"0")}:${String(timerSeconds%60).padStart(2,"0")}`},...v]);setTimer({running:false,started:null,elapsed:0,unit:"seconds"})};
  const records=[...selectedStudies.map(x=>({id:`s${x.id}`,kind:"学习",title:`${x.subject} · ${mins(x.minutes)}`,sub:x.note||"学习记录",action:()=>setModal({type:"study",record:x}),del:()=>remove("学习记录",()=>setStudies(v=>v.filter(y=>y.id!==x.id)))})),...selectedExpenses.map(x=>({id:`e${x.id}`,kind:"支出",title:`¥ ${x.amount.toFixed(2)} · ${x.category}`,sub:x.note||"账单记录",action:()=>setModal({type:"expense",record:x}),del:()=>remove("账单",()=>setExpenses(v=>v.filter(y=>y.id!==x.id)))})),...selectedWorkouts.map(x=>({id:`w${x.id}`,kind:"运动",title:`${x.type} · ${x.minutes} 分钟`,sub:x.distance?`${x.distance} 米`:x.note||"运动记录",action:()=>setModal({type:"workout",record:x}),del:()=>remove("运动记录",()=>setWorkouts(v=>v.filter(y=>y.id!==x.id)))}))];
  if(!ready)return <main className="shell"/>;
  return <main className="shell">
    <header className="topbar"><div><p className="brand">MY STUDY DASHBOARD</p><h1>{greeting}，无机盐</h1><p>{dateText(today)} · 先把今天过清楚</p></div><div className="top-actions"><button className="theme-toggle" onClick={()=>setThemeOpen(v=>!v)}>配色</button><button className="date-chip" onClick={()=>{setActiveDate(today);setTab("study")}}>今日计划</button>{themeOpen&&<div className="theme-menu">{THEMES.map(item=><button key={item.id} className={theme===item.id?"selected":""} onClick={()=>{setTheme(item.id);setThemeOpen(false)}}><i className={item.id}/>{item.name}</button>)}</div>}</div></header>
    {tab==="today"&&<div className="screen today-screen"><section className="hero-card"><div><p className="eyebrow">距离初试</p><strong>{days}<small>天</small></strong><p className="hero-copy">今天的每一次专注，都会留在你的进度里。</p></div><label>考试日<input type="date" value={target} onChange={e=>setTarget(e.target.value)}/></label></section><section className="progress-card"><div><span>今日完成度</span><b>{taskProgress}%</b></div><div className="progress-track"><i style={{width:`${taskProgress}%`}}/></div><p>{todayTasks.length?`${todayTasks.filter(x=>x.done).length} / ${todayTasks.length} 条任务已完成`:`今天还没有任务，写一条就开始。`}</p></section><section className="panel task-panel"><div className="panel-title"><div><p className="eyebrow">TODAY</p><h2>今天的任务</h2></div><button onClick={()=>setModal({type:"task"})}>＋ 添加</button></div>{todayTasks.length?<TaskRows tasks={todayTasks} subjects={SUBJECTS} onToggle={id=>setTasks(v=>v.map(x=>x.id===id?{...x,done:!x.done}:x))} onEdit={x=>setModal({type:"task",record:x})} onDelete={id=>remove("任务",()=>setTasks(v=>v.filter(x=>x.id!==id)))}/>:<div className="empty-state"><span>今天是一张新纸</span>{tasks.some(x=>x.date===yesterday)&&<button onClick={()=>{setActiveDate(yesterday);setTab("study")}}>查看昨天的任务</button>}</div>}</section><section className="quick-grid"><button onClick={()=>{setActiveDate(today);setModal({type:"study"})}}><i className="mint">◷</i><span>学习</span><b>{mins(todayMinutes)}</b></button><button onClick={()=>{setActiveDate(today);setModal({type:"expense"})}}><i className="peach">¥</i><span>支出</span><b>¥{todaySpend.toFixed(0)}</b></button><button onClick={()=>{setActiveDate(today);setModal({type:"workout"})}}><i className="lilac">⌁</i><span>运动</span><b>{todayMovement}m</b></button></section></div>}
    {tab==="study"&&<div className="screen"><section className="timer-card"><div className="panel-title"><div><p className="eyebrow">FOCUS</p><h2>专注计时</h2></div><span className="soft-pill">{focus}</span></div><div className="subject-tabs">{SUBJECTS.map(s=><button key={s.name} className={focus===s.name?"selected":""} onClick={()=>setFocus(s.name)}>{s.short}</button>)}</div><strong className="timer-number">{String(Math.floor(timerSeconds/60)).padStart(2,"0")}:{String(timerSeconds%60).padStart(2,"0")}</strong><p>{timer.running?"正在记录真实经过的时间":"开始后，息屏再回来也会校准时长"}</p><div className="timer-actions"><button onClick={()=>setTimer({running:false,started:null,elapsed:0,unit:"seconds"})}>归零</button><button className="primary" onClick={toggleTimer}>{timer.running?"暂停":"开始"}</button><button onClick={finishTimer} disabled={!timerMinutes}>完成</button></div></section><section className="date-row"><div><p className="eyebrow">DAILY PLAN</p><h2>{activeDate===today?"今天的任务":dateText(activeDate)}</h2></div><input type="date" value={activeDate} onChange={e=>setActiveDate(e.target.value)}/></section><section className="panel task-panel"><div className="panel-title"><h2>任务清单</h2><button onClick={()=>setModal({type:"task"})}>＋ 添加</button></div>{selectedTasks.length?<TaskRows tasks={selectedTasks} subjects={SUBJECTS} onToggle={id=>setTasks(v=>v.map(x=>x.id===id?{...x,done:!x.done}:x))} onEdit={x=>setModal({type:"task",record:x})} onDelete={id=>remove("任务",()=>setTasks(v=>v.filter(x=>x.id!==id)))}/>:<div className="empty-state"><span>这一天还没有写任务</span><button onClick={()=>setModal({type:"task"})}>补一条</button></div>}</section><section className="panel record-panel"><div className="panel-title"><h2>学习记录</h2><button onClick={()=>setModal({type:"study"})}>＋ 补记</button></div><Records rows={records.filter(x=>x.kind==="学习")}/></section></div>}
    {tab==="money"&&<div className="screen"><section className="money-hero"><p className="eyebrow">SPENDING</p><h2>今天花了多少</h2><b>¥{todaySpend.toFixed(2)}</b><button onClick={()=>setModal({type:"expense"})}>＋ 记一笔</button></section><section className="panel record-panel"><div className="panel-title"><div><p className="eyebrow">EXPENSES</p><h2>{dateText(activeDate)} 的账单</h2></div><input type="date" value={activeDate} onChange={e=>setActiveDate(e.target.value)}/></div><Records rows={records.filter(x=>x.kind==="支出")}/></section></div>}
    {tab==="sport"&&<div className="screen"><section className="sport-hero"><div><p className="eyebrow">MOVE & SWIM</p><h2>把运动也记下来</h2><p>本月已运动 {monthWorkouts.length} 次 · {monthWorkouts.reduce((s,x)=>s+x.minutes,0)} 分钟</p></div><button onClick={()=>setModal({type:"workout"})}>＋ 记录运动</button></section><div className="sport-stats"><article><span>本周次数</span><b>{workouts.filter(x=>new Date(`${x.date}T12:00:00`).getTime()>=Date.now()-6*86400000).length} 次</b></article><article><span>本周运动</span><b>{workouts.filter(x=>new Date(`${x.date}T12:00:00`).getTime()>=Date.now()-6*86400000).reduce((s,x)=>s+x.minutes,0)} min</b></article></div><section className="panel record-panel"><div className="panel-title"><div><p className="eyebrow">WORKOUT LOG</p><h2>{dateText(activeDate)} 的运动</h2></div><input type="date" value={activeDate} onChange={e=>setActiveDate(e.target.value)}/></div><Records rows={records.filter(x=>x.kind==="运动")}/></section></div>}
    {tab==="review"&&<div className="screen"><section className="review-header"><div><p className="eyebrow">MONTHLY REVIEW</p><h2>本月完整记录</h2><p>每天做了什么，都能在这里找到。</p></div><input type="month" value={reviewMonth} onChange={e=>setReviewMonth(e.target.value)}/></section><section className="metric-grid"><article><span>学习</span><b>{mins(monthStudies.reduce((s,x)=>s+x.minutes,0))}</b><small>{new Set(monthStudies.map(x=>x.date)).size} 天有记录</small></article><article><span>任务</span><b>{tasks.filter(x=>x.date.startsWith(reviewMonth)&&x.done).length}</b><small>条已完成</small></article><article><span>运动</span><b>{monthWorkouts.length}</b><small>次出现</small></article></section><section className="panel calendar-panel"><div className="panel-title"><h2>每日轨迹</h2><span>{monthDays.size} 天留下痕迹</span></div><div className="month-map">{Array.from({length:daysInMonth},(_,i)=>{const date=`${reviewMonth}-${String(i+1).padStart(2,"0")}`;return <button key={date} className={monthDays.has(date)?"filled":""} onClick={()=>{setActiveDate(date);setTab("study")}}>{i+1}</button>})}</div></section><section className="panel month-detail"><div className="panel-title"><div><p className="eyebrow">DAILY RECORDS</p><h2>每天做了什么</h2></div></div>{dailyDetails.length?<div className="daily-list">{dailyDetails.map(day=><button key={day.date} className="day-card" onClick={()=>{setActiveDate(day.date);setTab("study")}}><b>{dateText(day.date)}</b><span>{day.tasks.length?`任务 ${day.tasks.filter(x=>x.done).length}/${day.tasks.length}`:""}{day.studies.length?` · 学习 ${mins(day.studies.reduce((s,x)=>s+x.minutes,0))}`:""}{day.expenses.length?` · 支出 ¥${day.expenses.reduce((s,x)=>s+x.amount,0).toFixed(0)}`:""}{day.workouts.length?` · 运动 ${day.workouts.map(x=>x.type).join("、")}`:""}</span><i>查看 ›</i></button>)}</div>:<div className="empty-state">这个月还没有记录</div>}</section></div>}
    <nav className="bottom-nav">{([['today','今日'],['study','学习'],['money','记账'],['sport','运动'],['review','月度']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {modal&&<div className="overlay" onClick={()=>setModal(null)}><form className="sheet" onClick={e=>e.stopPropagation()} onSubmit={modal.type==="task"?saveTask:modal.type==="study"?saveStudy:modal.type==="expense"?saveExpense:saveWorkout}><div className="sheet-title"><h2>{modal.type==="task"?(editTask?"修改任务":"新增任务"):modal.type==="study"?(editStudy?"修改学习":"补记学习"):modal.type==="expense"?(editExpense?"修改账单":"记一笔"):editWorkout?"修改运动":"记录运动"}</h2><button type="button" onClick={()=>setModal(null)}>×</button></div>{modal.type==="task"&&<><label>科目<select name="subject" defaultValue={editTask?.subject||focus}>{SUBJECTS.map(x=><option key={x.name}>{x.name}</option>)}</select></label><label>任务内容<input name="text" required defaultValue={editTask?.text||""} placeholder="例如：概率论错题复盘" autoFocus/></label><label>日期<input name="date" type="date" defaultValue={editTask?.date||activeDate}/></label></>}{modal.type==="study"&&<><label>科目<select name="subject" defaultValue={editStudy?.subject||focus}>{SUBJECTS.map(x=><option key={x.name}>{x.name}</option>)}</select></label><label>时长（分钟）<input name="minutes" type="number" min="1" required defaultValue={editStudy?.minutes||""} autoFocus/></label><label>内容<input name="note" defaultValue={editStudy?.note||""} placeholder="学了什么？"/></label><label>日期<input name="date" type="date" defaultValue={editStudy?.date||activeDate}/></label></>}{modal.type==="expense"&&<><label>金额<input name="amount" type="number" step="0.01" required defaultValue={editExpense?.amount||""} autoFocus/></label><label>分类<select name="category" defaultValue={editExpense?.category||"餐饮"}><option>餐饮</option><option>交通</option><option>学习</option><option>运动</option><option>购物</option><option>其他</option></select></label><label>备注<input name="note" defaultValue={editExpense?.note||""} placeholder="买了什么？"/></label><label>日期<input name="date" type="date" defaultValue={editExpense?.date||activeDate}/></label></>}{modal.type==="workout"&&<><label>运动<select name="type" defaultValue={editWorkout?.type||"游泳"}><option>游泳</option><option>跑步</option><option>力量训练</option><option>散步</option></select></label><label>时长（分钟）<input name="minutes" type="number" min="1" required defaultValue={editWorkout?.minutes||""} autoFocus/></label><label>距离（米，可不填）<input name="distance" type="number" defaultValue={editWorkout?.distance||""}/></label><label>备注<input name="note" defaultValue={editWorkout?.note||""}/></label><label>日期<input name="date" type="date" defaultValue={editWorkout?.date||activeDate}/></label></>}<button className="primary full">保存</button></form></div>}
  </main>;
}

function TaskRows({tasks,subjects,onToggle,onEdit,onDelete}:{tasks:Task[];subjects:{name:Subject;color:string;short:string}[];onToggle:(id:number)=>void;onEdit:(task:Task)=>void;onDelete:(id:number)=>void}){return <div className="task-rows">{tasks.map(t=>{const s=subjects.find(x=>x.name===t.subject)!;return <article key={t.id} className={t.done?"done":""}><button className="tick" onClick={()=>onToggle(t.id)}>✓</button><i style={{background:s.color}}/><div><b>{t.text}</b><small>{t.subject}</small></div><button className="row-link" onClick={()=>onEdit(t)}>改</button><button className="row-link danger" onClick={()=>onDelete(t.id)}>删</button></article>})}</div>}
function Records({rows}:{rows:{id:string;kind:string;title:string;sub:string;action:()=>void;del:()=>void}[]}){if(!rows.length)return <div className="empty-state">这一天还没有这类记录</div>;return <div className="records">{rows.map(x=><article key={x.id}><span>{x.kind}</span><div><b>{x.title}</b><small>{x.sub}</small></div><button className="row-link" onClick={x.action}>修改</button><button className="row-link danger" onClick={x.del}>删除</button></article>)}</div>}
